In [49]:
###Data Manipulation Tasks (Pandas and Numpy)
#4.Pandas Data Manipulation
#Given a CSV file with sales data (sales.csv), perform the following tasks:
#•Load the data into a Pandas DataFrame.
#•Calculate the total sales for each product category.
#•Find the top 5 products with the highest sales.

In [51]:
##Load the data into a Pandas DataFrame

In [57]:
#Import libreries 

import pandas as pd
import numpy as np

In [55]:
#Load the data into a Pandas DataFrame

data = pd.read_excel(r"C:\Users\dell\Downloads\Sample_Sales_Data.xlsx")
data

ProductID ProductCategory ProductName  QuantitySold  PricePerUnit  \
0        101     Electronics      Laptop            50          1000   
1        102     Electronics  Smartphone           150           800   
2        103       Furniture        Sofa            20           500   
3        104       Furniture       Table            30           300   
4        105        Clothing     T-shirt           100            20   
5        106        Clothing       Jeans            60            40   
6        107        Clothing      Jacket            40            60   
7        108     Electronics  Headphones            70           100   
8        109       Furniture       Chair            15           150   
9        110     Electronics     Monitor            45           200   

   TotalSales  
0       50000  
1      120000  
2       10000  
3        9000  
4        2000  
5        2400  
6        2400  
7        7000  
8        2250  
9        9000

In [59]:
#Check how many unique products we have in ProductCategory column

data['ProductCategory'].unique()

array(['Electronics', 'Furniture', 'Clothing'], dtype=object)

In [45]:
Val1= data.sort_values(by= ["ProductCategory"])
Val1.head(11)

ProductID ProductCategory ProductName  QuantitySold  PricePerUnit  \
4        105        Clothing     T-shirt           100            20   
5        106        Clothing       Jeans            60            40   
6        107        Clothing      Jacket            40            60   
0        101     Electronics      Laptop            50          1000   
1        102     Electronics  Smartphone           150           800   
7        108     Electronics  Headphones            70           100   
9        110     Electronics     Monitor            45           200   
2        103       Furniture        Sofa            20           500   
3        104       Furniture       Table            30           300   
8        109       Furniture       Chair            15           150   

   TotalSales  
4        2000  
5        2400  
6        2400  
0       50000  
1      120000  
7        7000  
9        9000  
2       10000  
3        9000  
8        2250

In [61]:
#Calculate the total sales for Clothing product category.

f1 =Val1.iloc[:3]
SF1 = f1.sum()
SF1

ProductID                               318
ProductCategory    ClothingClothingClothing
ProductName              T-shirtJeansJacket
QuantitySold                            200
PricePerUnit                            120
TotalSales                             6800
dtype: object

In [63]:
#Calculate the total sales for Electronics product category.

f2 =Val1.iloc[3:7]
SF2 = f2.sum()
SF2

ProductID                                                   421
ProductCategory    ElectronicsElectronicsElectronicsElectronics
ProductName                   LaptopSmartphoneHeadphonesMonitor
QuantitySold                                                315
PricePerUnit                                               2100
TotalSales                                               186000
dtype: object

In [65]:
#Calculate the total sales for Furniture product category.

f3 =Val1.iloc[7:]
SF3 = f3.sum()
SF3

ProductID                                  316
ProductCategory    FurnitureFurnitureFurniture
ProductName                     SofaTableChair
QuantitySold                                65
PricePerUnit                               950
TotalSales                               21250
dtype: object

In [67]:
#•Find the top 5 products with the highest sales.

In [69]:
Val= data.sort_values(by= ["TotalSales"], ascending=[False])
Val.head()

ProductID ProductCategory ProductName  QuantitySold  PricePerUnit  \
1        102     Electronics  Smartphone           150           800   
0        101     Electronics      Laptop            50          1000   
2        103       Furniture        Sofa            20           500   
3        104       Furniture       Table            30           300   
9        110     Electronics     Monitor            45           200   

   TotalSales  
1      120000  
0       50000  
2       10000  
3        9000  
9        9000

In [ ]:
#5. Numpy Array Operations
#Create a 3x3 NumPy array with random integers. Perform the following operations:
#Compute the sum of all elements in the array.
#Find the mean and standard deviation of the elements.
#Normalize the array (subtract the mean and divide by the standard deviation).

In [71]:
#–Create a 3x3 NumPy array with random integers. Perform the following operations:

a = np.array([[10, 20, 30], [5, 15, 25], [3, 3, 3]])
a

array([[10, 20, 30],
       [ 5, 15, 25],
       [ 3,  3,  3]])

In [83]:
#Compute the sum of all elements in the array.

print("Sum of Arr : ", np.sum(a))

Sum of Arr :  114


In [87]:
#Find the mean and standard deviation of the elements.
#mean

M = np.mean(a)
M

12.666666666666666

In [89]:
#Standard Deviation
Stdd = np.std(a)
Stdd

9.76387901058454

In [91]:
#Normalize the array (subtract the mean and divide by the standard deviation).

Nor = []
for i in range(len(a)):
    result = (a[i] - M)/Stdd
    Nor.append(result)

In [93]:
Nor

[array([-0.2731155 ,  0.75106762,  1.77525073]),
 array([-0.78520705,  0.23897606,  1.26315917]),
 array([-0.99004368, -0.99004368, -0.99004368])]

In [95]:
#Normalization done